### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by lcarva** [mokshaproject/moksha#69]
Looks like in https://github.com/mokshaproject/moksha/commit/b60f6019d1e75816b87d72ad2de0576164c6b565 the call to `host.decode('utf-8')` causes the following traceback on python 3:

```
[2019-02-06 18:54:13][moksha.hub    INFO] connecting encrypted to 'xxxxx.yyyy.com' 61612 <moksha.hub.stomp.stomp.StompHubExtension object at 0x7fc332679da0>
Traceback (most recent call last):
  File "/usr/bin/fedmsg-hub-3", line 11, in <module>
    load_entry_point('fedmsg==1.1.1', 'console_scripts', 'fedmsg-hub')()
  File "/usr/lib/python3.7/site-packages/fedmsg/commands/hub.py", line 122, in hub
    command.execute()
  File "/usr/lib/python3.7/site-packages/fedmsg/commands/__init__.py", line 67, in execute
    return self.run()
  File "/usr/lib/python3.7/site-packages/fedmsg/commands/hub.py", line 100, in run
    framework=False,
  File "/usr/lib/python3.7/site-packages/moksha/hub/__init__.py", line 81, in main
    hub = CentralMokshaHub(config, consumers=consumers, producers=producers)
  File "/usr/lib/python3.7/site-packages/moksha/hub/hub.py", line 270, in __init__
    super(CentralMokshaHub, self).__init__(config)
  File "/usr/lib/python3.7/site-packages/moksha/hub/hub.py", line 126, in __init__
    ext(self, config) for ext in find_hub_extensions(config)
  File "/usr/lib/python3.7/site-packages/moksha/hub/hub.py", line 126, in <listcomp>
    ext(self, config) for ext in find_hub_extensions(config)
  File "/usr/lib/python3.7/site-packages/moksha/hub/stomp/stomp.py", line 74, in __init__
    self.connect(self.addresses[self.address_index], self.key, self.crt)
  File "/usr/lib/python3.7/site-packages/moksha/hub/stomp/stomp.py", line 94, in connect
    ssl_context = ssl.optionsForClientTLS(host.decode('utf-8'), clientCertificate=client_cert)
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by ralphbean** [comment]
@mikebonnet may have a patch for this.
