### ISSUE TITLE
fedmsg-hub service is being stopped on "Unexpected ACK"

### ISSUE THREAD

**Issue by hluk** [mokshaproject/moksha#74]
We started to get following errors.

```log
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: 2019-10-08 12:33:15,043 - stomper.Engine - ERROR - Received server error - messageUnexpected ACK received for message-id [ID\cbroker02.prod.example.com-39846-1570015736009-11\c454561\c0\c0\c1]
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: org.apache.activemq.transport.stomp.ProtocolException: Unexpected ACK received for message-id [ID:broker02.prod.example.com-39846-1570015736009-11:454561:0:0:1]
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: at org.apache.activemq.transport.stomp.ProtocolConverter.onStompAck(ProtocolConverter.java:475)
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: at org.apache.activemq.transport.stomp.ProtocolConverter.onStompCommand(ProtocolConverter.java:250)
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: at org.apache.activemq.transport.stomp.StompTransportFilter.onCommand(StompTransportFilter.java:85)
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: at org.apache.activemq.transport.tcp.SslTransport.doConsume(SslTransport.java:166)
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: at org.apache.activemq.transport.stomp.StompSslTransportFactory$1$1.doConsume(StompSslTransportFactory.java:70)
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:214)
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:196)
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: at java.lang.Thread.run(Thread.java:748)
Oct 08 12:33:15 resultsdb-updater.example.com fedmsg-hub[18340]: [2019-10-08 12:33:15][moksha.hub.stomp.protocol   ERROR] Requesting shutdown of hub for STOMP error.
```

It's just a guess, but this was caused by starting to use `/queue/Consumer.client-resultsdb-updater.prod.VirtualTopic.eng.ci.>` to replace lot of `/queue/Consumer.client-resultsdb-updater.{{ env }}.VirtualTopic.eng.ci.*.component-version.test.*` and `/queue/Consumer.client-resultsdb-updater.{{ env }}.VirtualTopic.eng.ci.component-version.test.complete`.

Current workaround is to set `Restart=always` for the service (`/usr/lib/systemd/system/fedmsg-hub.service`).

**Comment by ralphbean** [comment]
You have that `message-id` for the unexpected message.  Can you see any interesting pattern with them in datagrepper?

**Comment by ralphbean** [comment]
And, I'm curious to see how frequently this happens.  Take a look in kibana.  At regular intervals?

**Comment by hluk** [comment]
Looks like it's caused by the consumer not being able to process some messages - uncaught exception when accessing some fields in message body. After failing second time, the fedmsg-hub is stopped.

Not sure if that behavior is expected, but fedmsg-hub exits "cleanly," so systemd won't restart the service when `Restart=on-failure`.

**Comment by hluk** [comment]
Below is (obfuscated) log from fedmsg-hub service just before it's stopped by the issue. `<MESSAGE-ID>` is ID of message that is consumed multiple times even though it was successfully processed the first time.

Note: `stomp_ack_mode` mode is set to `client-individual`.

```log
2019-10-22 09:38:39,778 - moksha.hub - DEBUG - 'CIConsumer' thread 140377067165504 | Worker thread picking a message.
2019-10-22 09:38:39,778 - CIConsumer - INFO - Processing message: "<MESSAGE-ID>"
2019-10-22 09:38:39,779 - CIConsumer - WARNING - The message topic "/topic/VirtualTopic.eng.ci.brew-build.test.complete" uses old scheme not containing namespace from test case name "osci.brew-build.tier0.functional"
[2019-10-22 09:38:39][requests.packages.urllib3.connectionpool    INFO] Starting new HTTPS connection (1): resultsdb.example.com
2019-10-22 09:38:39,781 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): resultsdb.example.com
2019-10-22 09:38:40,777 - requests.packages.urllib3.connectionpool - DEBUG - "POST /api/v2.0/results HTTP/1.1" 201 1815
2019-10-22 09:38:40,780 - moksha.hub - DEBUG - 'CIConsumer' thread 140377067165504 | Going back to waiting on the incoming queue.  Message handled: True
[2019-10-22 09:38:40][moksha.hub.stomp.protocol WARNING] handled=None.  Responding with ACK
subscription:/queue/Consumer.client-resultsdb-updater.stage.VirtualTopic.eng.ci.*.test.*
message-id:<MESSAGE-ID>
2019-10-22 09:38:40,780 - moksha.hub.stomp.protocol - WARNING - handled=None.  Responding with ACK
subscription:/queue/Consumer.client-resultsdb-updater.stage.VirtualTopic.eng.ci.*.test.*
message-id:<MESSAGE-ID>
2019-10-22 09:38:40,781 - moksha.hub - DEBUG - 'CIConsumer' thread 140377067165504 | Worker thread picking a message.
2019-10-22 09:38:40,781 - CIConsumer - INFO - Processing message: "<MESSAGE-ID>"
2019-10-22 09:38:40,782 - CIConsumer - WARNING - The message topic "/topic/VirtualTopic.eng.ci.brew-build.test.complete" uses old scheme not containing namespace from test case name "osci.brew-build.tier0.functional"
[2019-10-22 09:38:40][requests.packages.urllib3.connectionpool    INFO] Starting new HTTPS connection (1): resultsdb.example.com
2019-10-22 09:38:40,783 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): resultsdb.example.com
2019-10-22 09:38:41,616 - requests.packages.urllib3.connectionpool - DEBUG - "POST /api/v2.0/results HTTP/1.1" 201 1815
2019-10-22 09:38:41,618 - moksha.hub - DEBUG - 'CIConsumer' thread 140377067165504 | Going back to waiting on the incoming queue.  Message handled: True
[2019-10-22 09:38:41][moksha.hub.stomp.protocol WARNING] handled=None.  Responding with ACK
subscription:/queue/Consumer.client-resultsdb-updater.stage.VirtualTopic.eng.ci.*.test.*
message-id:<MESSAGE-ID>
2019-10-22 09:38:41,619 - moksha.hub.stomp.protocol - WARNING - handled=None.  Responding with ACK
subscription:/queue/Consumer.client-resultsdb-updater.stage.VirtualTopic.eng.ci.*.test.*
message-id:<MESSAGE-ID>
2019-10-22 09:38:41,704 - moksha.hub - DEBUG - Got message without a topic: {...}, 'cmd': u'ERROR'}
2019-10-22 09:38:41,704 - stomper.Engine - ERROR - Received server error - messageUnexpected ACK received for message-id [<MESSAGE-ID>]
org.apache.activemq.transport.stomp.ProtocolException: Unexpected ACK received for message-id [<MESSAGE-ID>]
at org.apache.activemq.transport.stomp.ProtocolConverter.onStompAck(ProtocolConverter.java:475)
at org.apache.activemq.transport.stomp.ProtocolConverter.onStompCommand(ProtocolConverter.java:250)
at org.apache.activemq.transport.stomp.StompTransportFilter.onCommand(StompTransportFilter.java:85)
at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)
at org.apache.activemq.transport.tcp.SslTransport.doConsume(SslTransport.java:166)
at org.apache.activemq.transport.stomp.StompSslTransportFactory$1$1.doConsume(StompSslTransportFactory.java:70)
at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:214)
at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:196)
at java.lang.Thread.run(Thread.java:748)
[2019-10-22 09:38:41][moksha.hub.stomp.protocol   ERROR] Requesting shutdown of hub for STOMP error.
```

**Comment by hluk** [comment]
@ralphbean, @mikebonnet Any idea why is consumer receiving the same message twice?

And what does `[moksha.hub.stomp.protocol WARNING] handled=None.  Responding with ACK` mean?

**Comment by hluk** [comment]
Resolved by changing queue prefix.

From the notification email we got from admins (about too many messages in queue) it seems we were still subscribed to an old queue.

**Comment by hluk** [comment]
> And what does `[moksha.hub.stomp.protocol WARNING] handled=None. Responding with ACK` mean?

Oh, BTW, this means that we don't return `True`, `False` from `consume()` method. It doesn't have any side effects, but we will have to fix that to get rid of the warning.
